# name: Build and Zip Chrome Extension

# on:
#   workflow_dispatch:

# jobs:
#   build:
#     name: Build
#     timeout-minutes: 15
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out code
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 2
 
#       - name: Setup Node.js environment
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18
#           cache: 'yarn'
 
#       - name: Install dependencies
#         run: yarn
 
#       - name: Build Chrome
#         run: yarn build:chrome

#       - name: Upload Chrome extension artifacts
#         uses: actions/upload-artifact@v3
#         with:
#           name: vite-web-extension-chrome
#           path: dist_chrome
# .github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install

      - run: pnpm build:chrome && pnpm build:firefox

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist_chrome/**
            dist_firefox/**
